[project]
name = "automatheque.factrice"
version = "0.1.0"
description = "Librairie et app simplifiÃ©e d'envoi de mail"
authors = [{name = "Marc", email = "githubmarc@maj44.com"}]
license = {text = "GPLv3.0"}
requires-python = ">=3.8"
readme = "README.md"
dependencies = [
    "automatheque",
    "automatheque.schema>=0.9.5",
]

[project.urls]
Home = "https://github.com/jaegerbobomb/automatheque"
Repository = "https://github.com/jaegerbobomb/automatheque.git"

[project.scripts]
factrice = "automatheque.factrice.app:main"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
